version: "3.3"
services:
  web:
    image: coronarelief
    build: 
      context: .
      dockerfile: Dockerfile
    command: sh -c "python3 manage.py runserver 0.0.0.0:8001"
    ports:
      - "8001:8001"
    volumes: 
      - .:/code