# Generated by Django 3.0.5 on 2020-04-04 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='word_comissioner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relief_quantity', models.IntegerField(default=0)),
                ('city_name', models.CharField(blank=True, max_length=200)),
                ('word_number', models.IntegerField(blank=True, default=0)),
                ('contact', models.CharField(blank=True, max_length=200)),
                ('nid', models.CharField(max_length=20)),
                ('user_type', models.CharField(choices=[('Ministry_Relief', 'MINISTRY RELIEF'), ('City_Meyor', 'CITY MEYOR'), ('District_Comissioner', 'DISTRICT COMISSIONER'), ('Upazila_Officer', 'UPIZILA OFFICER'), ('Upazila_Uno', 'UPAZILA UNO'), ('Word_Commiossioner', 'WORD COMISSIONER'), ('Relief_Consumer', 'RELIEF CONSUMER')], max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='upazila_uno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relief_quantity', models.IntegerField(default=0)),
                ('contact', models.CharField(blank=True, max_length=200)),
                ('area', models.CharField(blank=True, max_length=200)),
                ('nid', models.CharField(max_length=20)),
                ('user_type', models.CharField(choices=[('Ministry_Relief', 'MINISTRY RELIEF'), ('City_Meyor', 'CITY MEYOR'), ('District_Comissioner', 'DISTRICT COMISSIONER'), ('Upazila_Officer', 'UPIZILA OFFICER'), ('Upazila_Uno', 'UPAZILA UNO'), ('Word_Commiossioner', 'WORD COMISSIONER'), ('Relief_Consumer', 'RELIEF CONSUMER')], max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='upazila_officer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relief_quantity', models.IntegerField(default=0)),
                ('contact', models.CharField(blank=True, max_length=200)),
                ('upazila_name', models.CharField(blank=True, max_length=200)),
                ('nid', models.CharField(max_length=20)),
                ('user_type', models.CharField(choices=[('Ministry_Relief', 'MINISTRY RELIEF'), ('City_Meyor', 'CITY MEYOR'), ('District_Comissioner', 'DISTRICT COMISSIONER'), ('Upazila_Officer', 'UPIZILA OFFICER'), ('Upazila_Uno', 'UPAZILA UNO'), ('Word_Commiossioner', 'WORD COMISSIONER'), ('Relief_Consumer', 'RELIEF CONSUMER')], max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='relief_consumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relief_quantity', models.IntegerField(default=0)),
                ('family_member', models.IntegerField(default=1)),
                ('nid', models.CharField(max_length=20)),
                ('user_type', models.CharField(choices=[('Ministry_Relief', 'MINISTRY RELIEF'), ('City_Meyor', 'CITY MEYOR'), ('District_Comissioner', 'DISTRICT COMISSIONER'), ('Upazila_Officer', 'UPIZILA OFFICER'), ('Upazila_Uno', 'UPAZILA UNO'), ('Word_Commiossioner', 'WORD COMISSIONER'), ('Relief_Consumer', 'RELIEF CONSUMER')], max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ministry_relief',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relief_quantity', models.IntegerField(default=0)),
                ('nid', models.CharField(max_length=20)),
                ('user_type', models.CharField(choices=[('Ministry_Relief', 'MINISTRY RELIEF'), ('City_Meyor', 'CITY MEYOR'), ('District_Comissioner', 'DISTRICT COMISSIONER'), ('Upazila_Officer', 'UPIZILA OFFICER'), ('Upazila_Uno', 'UPAZILA UNO'), ('Word_Commiossioner', 'WORD COMISSIONER'), ('Relief_Consumer', 'RELIEF CONSUMER')], max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='district_comissioner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relief_quantity', models.IntegerField(default=0)),
                ('contact', models.CharField(blank=True, max_length=200)),
                ('district_name', models.CharField(blank=True, max_length=200)),
                ('nid', models.CharField(max_length=20)),
                ('user_type', models.CharField(choices=[('Ministry_Relief', 'MINISTRY RELIEF'), ('City_Meyor', 'CITY MEYOR'), ('District_Comissioner', 'DISTRICT COMISSIONER'), ('Upazila_Officer', 'UPIZILA OFFICER'), ('Upazila_Uno', 'UPAZILA UNO'), ('Word_Commiossioner', 'WORD COMISSIONER'), ('Relief_Consumer', 'RELIEF CONSUMER')], max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='city_meyor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relief_quantity', models.IntegerField(default=0)),
                ('contact', models.CharField(blank=True, max_length=200)),
                ('elected_city', models.CharField(blank=True, max_length=200)),
                ('nid', models.CharField(max_length=20)),
                ('user_type', models.CharField(choices=[('Ministry_Relief', 'MINISTRY RELIEF'), ('City_Meyor', 'CITY MEYOR'), ('District_Comissioner', 'DISTRICT COMISSIONER'), ('Upazila_Officer', 'UPIZILA OFFICER'), ('Upazila_Uno', 'UPAZILA UNO'), ('Word_Commiossioner', 'WORD COMISSIONER'), ('Relief_Consumer', 'RELIEF CONSUMER')], max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
